# Generated by Django 5.0.7 on 2024-08-01 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('lname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('nin', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('role', models.CharField(blank=True, choices=[('Coach', 'Coach'), ('Head of delegation', 'Head of delegation'), ('Field of play officer', 'Field of play officer'), ('Medical', 'Medical'), ('Security', 'Security'), ('Young reporter', 'Young reporter'), ('Press', 'Press'), ('Volunteer', 'Volunteer'), ('Other', 'Other')], max_length=25, null=True)),
                ('photo', models.ImageField(blank=True, default='/images/profile.png', null=True, upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('U16', 'U16'), ('U18', 'U18'), ('U20', 'U20')], max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10, null=True)),
                ('athletes', models.ManyToManyField(to='accounts.athlete')),
                ('championship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.championship')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.school')),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.sport')),
            ],
        ),
    ]
