# Generated by Django 5.0.7 on 2024-08-05 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_official_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolteam',
            name='age',
        ),
        migrations.RemoveField(
            model_name='schoolteam',
            name='championship',
        ),
        migrations.RemoveField(
            model_name='schoolteam',
            name='status',
        ),
    ]
