# Generated by Django 5.0.7 on 2024-08-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_official_gender_alter_official_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='role',
            field=models.CharField(blank=True, choices=[('Coach', 'Coach'), ('Games teacher', 'Games teacher'), ('Head of delegation', 'Head of delegation'), ('Field of play officer', 'Field of play officer'), ('Medical', 'Medical'), ('Security', 'Security'), ('Young reporter', 'Young reporter'), ('Press', 'Press'), ('Volunteer', 'Volunteer'), ('Other', 'Other')], max_length=250, null=True),
        ),
    ]
