# Generated by Django 5.0.7 on 2024-08-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_official_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='role',
            field=models.CharField(blank=True, choices=[('Coach', 'Coach'), ('Games teacher', 'Games teacher'), ('Head of delegation', 'Head of delegation'), ('Field of play officer', 'Field of play officer'), ('Medical', 'Medical'), ('Security', 'Security'), ('Young reporter', 'Young reporter'), ('Press', 'Press'), ('Volunteer', 'Volunteer'), ('Secretariat', 'Secretariat'), ('Sports coordinators', 'Sports coordinators'), ('Refeere', 'Refeere'), ('Umpires', 'Umpires'), ('Matron', 'Matron'), ('Patron', 'Patron'), ('OR-TAMISEM Sports  coordinator', 'OR-TAMISEM Sports  coordinator'), ('MOSCASMoEST', 'MOSCASMoEST'), ('MoEST', 'MoEST'), ('UMISSETA/UMITASHUMTA chairperson', 'UMISSETA/UMITASHUMTA chairperson'), ('UMISSETA/UMITASHUMTA vice chairperson', 'UMISSETA/UMITASHUMTA vice chairperson'), ('UMISSETA secretary', 'UMISSETA secretary'), ('UMISSETA Treasury.', 'UMISSETA Treasury')], max_length=250, null=True),
        ),
    ]
