# Generated by Django 5.0.7 on 2024-08-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='photo',
            field=models.ImageField(default=1, upload_to='athlete_photos/'),
            preserve_default=False,
        ),
    ]
