# Generated by Django 5.0.7 on 2024-08-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_athlete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='classroom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
