# Generated by Django 5.0.7 on 2024-08-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_athlete_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('comittee', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='off_photos/')),
            ],
            options={
                'ordering': ['-fname'],
            },
        ),
    ]
