# Generated by Django 5.0.7 on 2024-08-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_noc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noc',
            name='comittee',
            field=models.CharField(choices=[('Technical ', 'Technical '), ('Welfare ', 'Welfare '), ('Protocol', 'Protocol'), ('Finance', 'Finance'), ('Competitions', 'Competitions'), ('Medical /Health', 'Medical /Health'), ('Security and Safety', 'Security and Safety'), ('Transport', 'Transport'), ('Corporate Relations', 'Corporate Relations'), ('Media', 'Media'), ('Secretariat', 'Secretariat')], max_length=50),
        ),
    ]
